sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t oxhe2038/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true oxhe2038/docker-react-app yarn test -- --coverage

after_success:
  - echo "Test Success"